### ISSUE TITLE
Create GET Orders

### ISSUE THREAD

**Issue by wmorgansoftware** [anthonymorast/AllyInvest.py#5]
I'm looking to introduce a method to GET all the orders for a particular account. URLs doesn't need a change as `get_post_order` will work. However, there's some implementation questions about consistency in returned values before going forward with a PR for this:

When the `raw_data` (using this terminology since that's what my personal version uses for what comes back at an equivalent of your `__to_format` though I only use JSON) comes back from Ally, `raw_data['response']['orderstatus']['order']` can be either a `list` of dicts, a `dict`, or a `False` type (can't remember the specific format; I have active orders right now that I'd rather not dump for the sake of writing this issue; can certainly do for the PR). Is this something that this package should make consistent, or something that the developer who is importing this package needs to account for?

Each order, whether in a dict or list of dicts, has one key of "fixmlmessage", with a value in FIXML format. I'm converting this message to a dict using `xmltodict` for my own use, but don't know if this package wants to do a similar conversion, or if that should be left up to the developer that uses this package. An answer to this question would go a long way towards also implementing the POST order, as that needs to be made FIXML as well, and whether that's the responsibility of this package or the developer.

**Comment by anthonymorast** [comment]
Excellent questions.

For your last question, I think the FIXML stuff should definitely be converted to a user-friendly format (this is done in the reverse in the `order_common_stock` method). I really would prefer ordinary developers to not have to care about FIX.

As for your first question, if I recall correctly, the API wrapper more or less just returns the raw JSON/XML that comes out of Ally. Since there will probably be some FIX parsing in this case, it wouldn't hurt to convert any of the formats to JSON (as I expect most people to ignore the XML formatting) and let the developer deal with the details.

One thing I was working on when I was more active with this project was the `ally/request` and `ally/response` classes. The idea here is that the API requests and responses are wrapped up in Python classes which are more user-friendly. For example

account holdings request:
https://github.com/anthonymorast/AllyInvest.py/blob/master/ally/requests/account_holdings.py

account holdings response:
https://github.com/anthonymorast/AllyInvest.py/blob/master/ally/responses/account_holdings.py

there is example usage in the `examples/example.py` file.

You might consider implementing an account orders response/request and wrapping your parsing into that (if you'd like to). Otherwise, I would just parse the FIX into JSON and return the JSON and if the API returns a False type for some reason, maybe just return empty JSON.

**Comment by wmorgansoftware** [comment]
OK, sounds good. I can do both implementations, as the legacy continues to exist, and now that I've converted to using your package (gotta love how flask_dance forces you to have a HTTP request making debugging quite annoying), I've been using the legacy.

I'm going to have to update URLs after all, as the URL that's there forces XML instead of allowing for JSON.

**Comment by anthonymorast** [comment]
Sounds good. Thanks for your feedback/contribution. I look forward to your PR.

**Comment by wmorgansoftware** [comment]
Tried to push a new branch up to the project, and the terminal response is that I don't have permission to do so. I know I can push on my own projects. Would it be OK to put up a new branch with these proposed changes?

**Comment by anthonymorast** [comment]
I think you have to submit a [pull request](https://github.com/anthonymorast/AllyInvest.py/pulls). Do you have your own fork of the repository with your changes?

If so, from your fork you should be able to go to the Pull Request tab and click the New Pull Request button to submit one to the main branch of this project.

**Comment by anthonymorast** [comment]
If not, you should fork the repository, add your changes, and then submit the request.

**Comment by wmorgansoftware** [comment]
OK, should be up with #6 .

**Comment by anthonymorast** [comment]
Looks good. Thanks again for the contribution!
